spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wm?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 050698PL
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true